apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: production-clickhouse
spec:
  defaults:
  configuration:
    #Configure external ZooKeeper (or ClickHouseKeeper if you use that CRD)
    zookeeper:
      nodes:
        - host: chk-clickhouse-keeper-default-0-0.zookeeper.svc.cluster.local
          port: 2181
        - host: chk-clickhouse-keeper-default-0-1.zookeeper.svc.cluster.local
          port: 2181
        - host: chk-clickhouse-keeper-default-0-2.zookeeper.svc.cluster.local
          port: 2181
      session_timeout_ms: 30000
      operation_timeout_ms: 10000
      root: "/clickhouse"
    clusters:
      - name: production
        layout:
          shardsCount: 2
          replicasCount: 2
        templates:
          podTemplate: clickhouse-stable
          volumeClaimTemplate: clickhouse-storage
  templates:
    podTemplates:
      - name: clickhouse-stable
        spec:
          containers:
            - name: clickhouse
              image: altinity/clickhouse-server:24.3.5.47.altinitystable
              volumeMounts:
                - name: clickhouse-storage
                  mountPath: /var/lib/clickhouse
    volumeClaimTemplates:
      - name: clickhouse-storage
        spec:
          storageClassName: standard
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
